### ISSUE TITLE
No output for 7k images with Vision

### ISSUE THREAD

**Issue by Giuliagiorgi** [jason-chao/memespector-gui#1] opened 2021-06-02 08:13 UTC
Hello, thank you for this amazing GUI :)

I have run into an issue when trying to process around 7'000 images with Vision API. The issue is that when the Memespector is finished processing them, the programme closes automatically (with no confirmation pop-up window) and produces no .json or .csv. I have tried with less images (20) and it worked like a charm. I have tried again with the bigger dataset and the same as before (sudden closure, no output) happened. 
I know the images have been processed because looking at Vision API I can see differences in the upcoming payments (:D). 

Thank you!

**Comment by jason-chao** [comment] 2021-06-02 09:50
Thank you for letting me know the issue.  I am sorry to hear about your experience.  I will look into it right away.  

In the meantime, it would be great if you could tell me a few things as follows.

1. What APIs did you enable?  Did you use Google Vision API only?
2. What is the total size of your 7 000 images?
3. Is your computer a Mac or a PC (Windows)? 
4. What is the model / specification of your computer? 

Thanks a lot!

**Comment by jason-chao** [comment] 2021-06-02 20:39
Please download and try [the latest version 0.2.3 beta](https://github.com/jason-chao/memespector-gui/releases).  Version 0.2.3 beta automatically saves the results to the output files every 15 seconds while the images are being processed. So, now even if the application happens to crash in the middle of the process, you will only lose the last 15 seconds' results at most.

In case the application quits unexpectedly again, you will find the unprocessed images, which have empty result values, in the output CSV file. Please copy the image locations without result values, paste them to the Memespector GUI, and run again.

Also, I found that the Image Sources box in the centre consumes quite a lot of memory if too many files are added to the GUI.  Now, image locations will not be shown in full if you add a folder or a text file as an image source.

I tested Memespector GUI with 8 000 images without a problem. Therefore, there does not seem to be a fixed number on how many images Memespector GUI can handle. The capacity of Memespector GUI to process large amounts of images depends on the specification of the computers.  I am sorry for being unable to suggest how many images you may add to Memespector GUI.  You may need to find out for yourself how many images your computer can handle in one go. 

The most probable cause for the application closing expectedly is that the computer was low on memory. I hope that version 0.2.3 beta will help resolve this problem.

**Comment by jason-chao** [comment] 2021-06-08 00:52
I can confirm that [the latest version 0.2.3 beta](https://github.com/jason-chao/memespector-gui/releases/tag/v0.2.3beta) has resolved this issue by changing a display behaviour to reduce memory footprint.  In a low-RAM environment, we replicated the problem of the application closing unexpectedly while processing a large number of images. This is caused by an issue with the cross-platform UI library. The application would consume an unusual amount of memory when too much text is displayed in a textbox.

From version 0.2.3 beta, the locations of image files inside the folder (and its subfolders) do not have to be displayed in the box in order to be processed. If a user adds a folder, only the location of the selected (outermost) folder will be displayed in the Image Sources box. If a user selects more than 256 image files, the textbox will only display the first 256 of them by default.  All selected images will be processed regardless of how many are shown in the textbox.  The README has been updated accordingly to explain the new display behaviour.

In addition, version 0.2.3 beta automatically saves the results to the output files every 15 seconds while the images are being processed.  So, even if the application happens to crash in the middle of the process for some other reason, the user will lose the last 15 seconds' results at most.

**Closed as completed by jason-chao** 2021-06-08 00:52 UTC
